version: "3.8"
services:
  roach1:
    build:
      context: ./cockroach
    hostname: roach1
    ports:
      - "26257:26257"
      - "8080:8080"
    command: [ "start", "--join=roach1,roach2,roach3", "--advertise-addr=roach1", "--store=/cockroach/data", "--certs-dir=/cockroach/certs" ]
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - roach1-data:/cockroach/data/:Z
      - roach-certs:/cockroach/certs/:z
    networks:
      roachnet:
  roach2:
    build:
      context: ./cockroach
    hostname: roach2
    #ports:
    #  - "26257:26257"
    #  - "8080:8080"
    command: [ "start", "--join=roach1,roach2,roach3", "--advertise-addr=roach2", "--store=/cockroach/data", "--certs-dir=/cockroach/certs" ]
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - roach2-data:/cockroach/data/:Z
      - roach-certs:/cockroach/certs/:z
    networks:
      roachnet:
  roach3:
    build:
      context: ./cockroach
    hostname: roach3
    #ports:
    #  - "26257:26257"
    #  - "8080:8080"
    command: [ "start", "--join=roach1,roach2,roach3", "--advertise-addr=roach3", "--store=/cockroach/data", "--certs-dir=/cockroach/certs" ]
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - roach3-data:/cockroach/data/:Z
      - roach-certs:/cockroach/certs/:z
    networks:
      roachnet:

volumes:
  roach1-data:
  roach2-data:
  roach3-data:
  roach-certs:

networks:
  roachnet:
