version: "3.8"
services:
  roach1:
    image: cockroachdb/cockroach:v20.2.7
    hostname: roach1
    ports:
      - "26257:26257"
      - "8080:8080"
    command: [ "start", "--insecure", "--join=roach1,roach2,roach3" ]
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - roach1-data:/cockroach/cockroach-data/
    networks:
      roachnet:
  roach2:
    image: cockroachdb/cockroach:v20.2.7
    hostname: roach2
    #ports:
    #  - "26257:26257"
    #  - "8080:8080"
    command: [ "start", "--insecure", "--join=roach1,roach2,roach3" ]
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - roach2-data:/cockroach/cockroach-data/
    networks:
      roachnet:
  roach3:
    image: cockroachdb/cockroach:v20.2.7
    hostname: roach3
    #ports:
    #  - "26257:26257"
    #  - "8080:8080"
    command: [ "start", "--insecure", "--join=roach1,roach2,roach3" ]
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - roach3-data:/cockroach/cockroach-data/
    networks:
      roachnet:

volumes:
  roach1-data:
  roach2-data:
  roach3-data:

networks:
  roachnet:
